# Generated by Django 4.2.5 on 2023-09-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='Reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='stand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.stand'),
            preserve_default=False,
        ),
    ]
